---
abstract: 'Low-Dependency Modules for interacting with InterMine Webservice APIs'
author:
  - 'Alex Kalderimis <dev@intermine.org>'
build_requires:
  Test::More: 0.9
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Webservice-InterMine-Simple
provides:
  Webservice::InterMine::Simple:
    file: lib/Webservice/InterMine/Simple.pm
    version: 0.9800
  Webservice::InterMine::Simple::Query:
    file: lib/Webservice/InterMine/Simple/Query.pm
    version: 0
  Webservice::InterMine::Simple::Service:
    file: lib/Webservice/InterMine/Simple/Service.pm
    version: 0
  Webservice::InterMine::Simple::Template:
    file: lib/Webservice/InterMine/Simple/Template.pm
    version: 0
requires:
  LWP: 5.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.9800
