language: java
env:
    - TEST_SUITE=model
#    - TEST_SUITE=objectstore
    - TEST_SUITE=integrate
    - TEST_SUITE=api
    - TEST_SUITE=pathquery
    - TEST_SUITE=web
#    - TEST_SUITE=bio
    - TEST_SUITE=selenium
    - TEST_SUITE=checkstyle
jdk:
    - oraclejdk7
#    - openjdk7
#    - openjdk6
before_script:
    - ./config/travis.init.sh
before_install:
    - "export DISPLAY=:99.0"
    - ./config/travis-before-install.sh
script:
    - ./config/travis-run.sh

# after_failure:
#   - config/upload_artifacts.sh
# notifications:
#   irc:
#       channels:
#           - "chat.freenode.net#intermine-ci"
#       on_success: change
#       on_error: always

