language: java
jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6
env:
    ANT_OPTS='-server'
before_script:
    - "export DISPLAY=:99.0"
    - "export TOMCAT_VERSION=7.0.53"
    - psql -c 'create database notxmltest;' -U postgres
    - psql -c 'create database truncunittest;' -U postgres
    - psql -c 'create database flatmodetest;' -U postgres
    - psql -c 'create database fulldatatest;' -U postgres
    - psql -c 'create database userprofiletest;' -U postgres
    - psql -c 'create database unittest;' -U postgres
    - psql -c 'create database biotest;' -U postgres
    - psql -c 'create database biofulldatatest;' -U postgres
    - mkdir ~/.intermine
    - cp config/ci.properties ~/.intermine/intermine-test.properties
    - sed -i 's/PG_USER/postgres/' ~/.intermine/intermine-test.properties
    - cp ~/.intermine/intermine-test.properties ~/.intermine/testmodel.properties
    - cp config/ci-bio.properties ~/.intermine/intermine-bio-test.properties
    - sed -i 's/PG_USER/postgres/' ~/.intermine/intermine-bio-test.properties
    - pip install -r testmodel/webapp/selenium/requirements.txt
    - sh config/download_and_configure_tomcat.sh
    - sh -e /etc/init.d/xvfb start
    - "sh apache-tomcat-${TOMCAT_VERSION}/bin/startup.sh 2>&1 &"
    - sleep 3
    - ant -f bio/test-all/dbmodel/build.xml build-db
script:
    - ant -f intermine/objectstore/test/build.xml 2>&1 | tee >(grep FAILED | sed -e 's/^/[objectstore] /' >> failures.list)
    - ant -f intermine/integrate/test/build.xml 2>&1 | tee >(grep FAILED | sed -e 's/^/[integrate] /' >> failures.list)
    - ant -f intermine/pathquery/test/build.xml 2>&1 | tee >(grep FAILED | sed -e 's/^/[pathquery] /' >> failures.list)
    - ant -f intermine/api/test/build.xml 2>&1 | tee >(grep FAILED | sed -e 's/^/[api] /' >> failures.list)
    - ant -f intermine/web/test/build.xml 2>&1 | tee >(grep FAILED | sed -e 's/^/[web] /' >> failures.list)
    - cat failures.list
    - (cd testmodel; PSQL_USER=postgres sh setup.sh)
    - sleep 10
    - (cd testmodel/webapp/selenium; nosetests)
    - test ! -s failures.list

