language: python # needed to get access to virtualenv
env:
    global:
        - TESTMODEL_URL=http://localhost:8080/intermine-demo
        - TESTMODEL_PATH=intermine-demo
    matrix:
        - TEST_SUITE=selenium
        - TEST_SUITE=ws-integration CLIENT=JS
        - TEST_SUITE=ws-integration CLIENT=PY
        - TEST_SUITE=model
#       - TEST_SUITE=objectstore
        - TEST_SUITE=integrate
        - TEST_SUITE=pathquery
        - TEST_SUITE=api
        - TEST_SUITE=web
        - TEST_SUITE=bio
        - TEST_SUITE=checkstyle
sudo: false # use container based infrastructure
jdk:
    - openjdk7
    - openjdk6
before_script:
    - ./config/travis/init.sh
before_install:
    - "export DISPLAY=:99.0"
    - ./config/travis/before-install.sh
script:
    - ./config/travis/run.sh
notifications:
  irc:
      channels:
          - "chat.freenode.net#intermine-ci"
      on_success: change
      on_error: change

