language: java
jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6
before_script:
    - psql -c 'create database notxmltest;' -U postgres
    - psql -c 'create database truncunittest;' -U postgres
    - psql -c 'create database flatmodetest;' -U postgres
    - psql -c 'create database fulldatatest;' -U postgres
    - psql -c 'create database userprofiletest;' -U postgres
    - psql -c 'create database unittest;' -U postgres
    - psql -c 'create database biotest;' -U postgres
    - psql -c 'create database biofulldatatest;' -U postgres
    - mkdir ~/.intermine
    - cp config/travis.properties ~/.intermine/intermine-test.properties
    - cp config/travis-bio.properties ~/.intermine/intermine-bio-test.properties
    - ant -f bio/test-all/dbmodel/build.xml build-db
script:
    - ant -f intermine/objectstore/test/build.xml
    - ant -f intermine/integrate/test/build.xml
    - ant -f bio/sources/uniprot/build.xml
