# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "WebReports"

project:
    title: "Cross-Project Reports"
    spiel: "These reports are intended to help InterMine data-warehouse maintainers by providing an overview on their data and that of their collaborators"

models: 
    title: "Model Comparison"
    spiel: "A comparison of models"

mines:
    YeastMine: "http://yeastmine.yeastgenome.org:8080/yeastmine"
    RatMine: "http://ratmine.mcw.edu/ratmine"
    FlyMine: "http://flymine.org/query"
    modMine: "http://intermine.modencode.org/query"
    Zfin: "http://zmine.zfin.org/zfinmine"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

