log_dir: "/micklem/data/download_logs"
data_dir: "/micklem/data"

default_sources:
  - "AffyProbes"
  - "Biogrid"
  - "EnsemblCompara"
  - "FlyAnatomyOntology"
  - "FlyAtlas"
  - "FlyBaseFasta"
  - "FlyBaseOrthologs"
  - "FlyOntologies"
  - "GoAnnotation"
  - "Intact"
  - "IntactVocabulary"
  - "Interpro"
  - "InterproGo"
  - "Kegg"
  - "PDB"
  - "PsiOntology"
  - "PubMed"
  - "Reactome"
  - "RedFly"
  - "Uniprot"
  - "WormbaseRNAi"
  - "WormIdentifiers"

Uniprot:
    organisms:
        - 10090 
        - 6239 
        - 7165 
        - 7217 
        - 7227 
        - 7955 
        - 559292
    excluded_organisms:
        - 63221
