log_dir: "download-tests/download_logs"
data_dir: "download-tests"

default_sources:
  - "AffyProbes"
  - "Biogrid"
  - "EnsemblCompara"
  - "FlyAnatomyOntology"
  - "FlyAtlas"
  - "FlyBaseFasta"
  - "FlyBaseOrthologs"
  - "FlyOntologies"
  - "GoAnnotation"
  - "Intact"
  - "IntactVocabulary"
  - "Interpro"
  - "InterproGo"
  - "Kegg"
  - "PDB"
  - "PsiOntology"
  - "PubMed"
  - "Reactome"
  - "RedFly"
  - "Uniprot"
  - "WormbaseRNAi"
  - "WormIdentifiers"
